// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartNutriTracker.Back.Database;

#nullable disable

namespace SmartNutriTracker.Back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Alimento", b =>
                {
                    b.Property<int>("AlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlimentoId"));

                    b.Property<int>("Calorias")
                        .HasColumnType("integer");

                    b.Property<decimal>("Carbohidratos")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Grasas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Proteinas")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("AlimentoId");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstudianteId"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ResultadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoAccionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("ResultadoId");

                    b.HasIndex("TipoAccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.MenuAlimento", b =>
                {
                    b.Property<int>("MenuAlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuAlimentoId"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.HasKey("MenuAlimentoId");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuAlimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.RegistroAlimento", b =>
                {
                    b.Property<int>("RegistroAlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroAlimentoId"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("RegistroHabitoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoComidaId")
                        .HasColumnType("integer");

                    b.HasKey("RegistroAlimentoId");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("RegistroHabitoId");

                    b.HasIndex("TipoComidaId");

                    b.ToTable("RegistroAlimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.RegistroHabito", b =>
                {
                    b.Property<int>("RegistroHabitoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroHabitoId"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegistroHabitoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("RegistroHabitos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.TipoAccion", b =>
                {
                    b.Property<int>("TipoAccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoAccionId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoAccionId");

                    b.ToTable("TiposAccion");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.TipoComida", b =>
                {
                    b.Property<int>("TipoComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoComidaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoComidaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposComida");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.TipoResultado", b =>
                {
                    b.Property<int>("TipoResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoResultadoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoResultadoId");

                    b.ToTable("TiposResultado");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Log", b =>
                {
                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.TipoResultado", "Resultado")
                        .WithMany("Logs")
                        .HasForeignKey("ResultadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.TipoAccion", "TipoAccion")
                        .WithMany("Logs")
                        .HasForeignKey("TipoAccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.Usuario", "Usuario")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Resultado");

                    b.Navigation("TipoAccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.MenuAlimento", b =>
                {
                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.Alimento", "Alimento")
                        .WithMany("MenuAlimentos")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.Menu", "Menu")
                        .WithMany("MenuAlimentos")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.RegistroAlimento", b =>
                {
                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.Alimento", "Alimento")
                        .WithMany("RegistroAlimentos")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.RegistroHabito", "RegistroHabito")
                        .WithMany("RegistroAlimentos")
                        .HasForeignKey("RegistroHabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.TipoComida", "TipoComida")
                        .WithMany("RegistroAlimentos")
                        .HasForeignKey("TipoComidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("RegistroHabito");

                    b.Navigation("TipoComida");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.RegistroHabito", b =>
                {
                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.Estudiante", "Estudiante")
                        .WithMany("RegistroHabitos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Usuario", b =>
                {
                    b.HasOne("SmartNutriTracker.Back.Models.BaseModels.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Alimento", b =>
                {
                    b.Navigation("MenuAlimentos");

                    b.Navigation("RegistroAlimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Estudiante", b =>
                {
                    b.Navigation("RegistroHabitos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Menu", b =>
                {
                    b.Navigation("MenuAlimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.RegistroHabito", b =>
                {
                    b.Navigation("RegistroAlimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.TipoAccion", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.TipoComida", b =>
                {
                    b.Navigation("RegistroAlimentos");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.TipoResultado", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SmartNutriTracker.Back.Models.BaseModels.Usuario", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
